#!/bin/bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure the redirection
sudo sed -i 's/location \/ {/location \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }\n\n    location \/ {/' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
