#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname
hostname=$(hostname)

# Configure Nginx to include custom HTTP response header
sudo sed -i "/server_name _;/a \        add_header X-Served-By $hostname;" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
