#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install haproxy
echo "frontend  Ibrahim-frontend
        bind *:80
        mode http
        default_backend Ibrahim-backend
backend Ibrahim-backend
        balance roundrobin
        server web-01 52.91.124.74:80 check
        server web-02 54.87.234.240:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
